export enum MessageTypeEnum {
	PLAYER_ACTION = 'PLAYER_ACTION',
	PING = 'PING',
	PONG = 'PONG',
	READY = 'READY',
	RESET_TIMEOUT = 'RESET_TIMEOUT',
	EDIT_ROOM = 'EDIT_ROOM',
	MESSAGE = 'MESSAGE',
	PLAYERS_WAITING = 'PLAYERS_WAITING',
	RANKED_SEAT = 'RANKED_SEAT',
}
