export enum MessageTypeEnum {
	PLAYER_ACTION = 'PLAYER_ACTION',
	PING = 'PING',
	PONG = 'PONG',
	READY = 'READY',
	TIMEOUT = 'TIMEOUT',
	RESET_TIMEOUT = 'RESET_TIMEOUT',
	EDIT_ROOM = 'EDIT_ROOM',
	MESSAGE = 'MESSAGE',
}
