name: Publish
on:
  push:
    branches:
      - main
      - test-lerna

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Use NodeJS 14'
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 'Version and publish' # Interesting step
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          npx lerna version --conventional-commits --yes
