name: Release using conventional commits (master branch)

on:
  push:
    branches:
      - feature/*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: conventional changelog action
        id: changelog
        uses: TriPSs/conventional-changelog-action@latest
        with:
          github-token: ${{ secrets.github_token }}
          output-file: 'MY_CUSTOM_CHANGELOG.md'
